version: "3"
services:
  web:
    # replace saubhatta/firsttry:latest with your name and image details
    image: saubhatta/firsttry:latest
    deploy:
      replicas: 6
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "4000:80"
    networks:
      - webnet
networks:
  webnet:
